### ISSUE TITLE
Can't add goal, page just refreshes and no new goal added and all input lost

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [MoneyMap-Project/MoneyMap#100]
Before submit
![image](https://github.com/user-attachments/assets/4c7cf7a2-f72a-4c7f-b813-42c4204f7c7b)
After submit
![image](https://github.com/user-attachments/assets/999c8d0f-1e4d-4a07-87ec-f454e68dd3b1)

**Comment by JaofourthsOhappy** [comment]
Fixed. On branch fix-bug-bounty1
