### ISSUE TITLE
Money amount goes off screen when the value is too large.

### ISSUE THREAD

**Issue by KhunakornP** [MoneyMap-Project/MoneyMap#101]
## **Bug**
When adding money flow the money amount goes off screen when the value is too large.
Money flow also doesn't support money amounts greater than or equal to 100,000,000.00 baht.

## **How To Reproduce**
1. Go to add money flow
2. Add a large amount of money

## Additional notes.
I would say that even though not every one is a billionaire this amount of money can happen with corporations and investors so I think that you should add some support for large amounts of money.

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

## **Screenshots**
![money](https://github.com/user-attachments/assets/22a92017-3e05-42b4-99dc-cc7bdc43fac1)

**Comment by JaofourthsOhappy** [comment]
Fixed. On branch fix-bug-bounty1
