### ISSUE TITLE
You can create multiple of the same entry by spamming the create button

### ISSUE THREAD

**Issue by KhunakornP** [MoneyMap-Project/MoneyMap#103]
## **Bug**
When adding money flow you can repeatedly click the submit button to create more entries.

## **How To Reproduce**
1. Go to add money flow
2. Fill out you details
3. Click add new money flow many times

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

## **Screenshots**
![spam](https://github.com/user-attachments/assets/b99abcd2-40a6-4803-9a9b-0736b52230c8)

**Comment by JaofourthsOhappy** [comment]
Fixed. On branch fix-bug-bounty1
