### ISSUE TITLE
Large text in money flow description breaks summary container layout

### ISSUE THREAD

**Issue by PHIMNADA024** [MoneyMap-Project/MoneyMap#104]
## The problem
When entering a large amount of text in the description field for a money flow entry, the text exceeds the boundaries of the summary container, disrupting the layout. There is no character limit or proper text wrapping in place to prevent this issue.

## How to reproduce the problem
1. Navigate to the Income & Expenses page.
2. Click on Add Your Money Flow Of The Day.
3. Enter a large amount of text in the description field for the money flow.
4. Observe that the text breaks out of the summary container.

![image](https://github.com/user-attachments/assets/0687760f-bdfb-49e6-8e87-0730baf779e6)

**Comment by PHIMNADA024** [comment]
**Additional:** I noticed that the Goals tab also lacks a character limit, causing the text to break out of the summary container as well.

**Comment by colarrbear** [comment]
Duplicates #101
