### ISSUE TITLE
Google login doesn't work

### ISSUE THREAD

**Issue by KhunakornP** [MoneyMap-Project/MoneyMap#95]
## **Bug**
Google login returns Server Error: 500

## **How To Reproduce**
1. Click login
2. Click login with google
3. Input your credentials

## **Expected behavior**
The website logs me in with my google account

## **Screenshots**
![google login](https://github.com/user-attachments/assets/49b77e7f-4700-46df-9af9-07661f0da5cb)

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

**Comment by colarrbear** [comment]
It’s finally worked ^_^
