### ISSUE TITLE
Manually inputting query params in history page causes a server error

### ISSUE THREAD

**Issue by KhunakornP** [MoneyMap-Project/MoneyMap#96]
## **Bug**
When manually adjusting the query params for start date and end date in the income and expense history the site returns Server Error: 500

## **How To Reproduce**
1. Go to financial history page
2. Enter any values that isn't a date with the format mm-dd-yy into the query params startDate & endDate

## **Expected behavior**
The website returns no data available or some error message for that date.

## **Screenshots**
![calendar](https://github.com/user-attachments/assets/c54bd91b-a088-47be-85f2-2d6232d0c1b6)

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

**Comment by JaofourthsOhappy** [comment]
Fixed.
