### ISSUE TITLE
[ENHANCEMENT] No icon in tab

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [MoneyMap-Project/MoneyMap#98]
There's no icon in the browser tab 
![image](https://github.com/user-attachments/assets/3bbf4193-d9bc-475c-b2a9-8403384ed63e)

Is this intentional?  
I would know to know which tabs are from this site since the text won't be visible if I have a lot of tabs and an icon would help.

**Comment by colarrbear** [comment]
Thanks. We're working on it!

**Comment by JaofourthsOhappy** [comment]
Fixed. On branch fix-bug-bounty1
